Fix:  The authorization code authentication error and the redirect URI selection is incorrect
spring-projects/spring-authorization-server pull request #1013
Opened 2022-12-18 06:53 UTC by leshalv

#1012

2023-01-10 20:06 UTC, jgrandja requested changes
Thank you for the PR @leshalv.

Please see the review comment and also please add a test to confirm the fix.

2023-01-10 20:06 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java
> +		OAuth2AuthorizationRequest authorizationRequest = OAuth2AuthorizationRequest.authorizationCode()
Please revert all changes and instead add parameter `OAuth2AuthorizationCodeRequestAuthenticationToken authorizationCodeRequestAuthentication` to `resolveRedirectUri()` allowing usage of `authorizationCodeRequestAuthentication.redirectUri`.

2023-01-12 00:56 UTC, leshalv commented
Ok, I've made the modification.

2023-01-16 19:47 UTC, jgrandja requested changes
Thanks for the updates @leshalv. Please see review comment for minor formatting changes.

Also, before we merge this, we need a test the proves the fix has been applied. You should be able to modify the existing test `OAuth2AuthorizationCodeRequestAuthenticationProviderTests.authenticateWhenPkceRequiredAndMissingCodeChallengeThenThrowOAuth2AuthorizationCodeRequestAuthenticationException()` to demonstrate the fix was applied. Thanks.

2023-01-16 19:47 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java
> +		String redirectUri = resolveRedirectUri(authorizationCodeRequestAuthentication,authorizationRequest, registeredClient);
Please ensure spacing between parameter values.

2023-01-16 19:47 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java
> +	private static String resolveRedirectUri(OAuth2AuthorizationCodeRequestAuthenticationToken authorizationCodeRequestAuthentication,OAuth2AuthorizationRequest authorizationRequest, RegisteredClient re
Please ensure spacing between parameter values.

2023-01-16 19:47 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeRequestAuthenticationProvider.java
> +		if (authorizationCodeRequestAuthentication!=null && StringUtils.hasText(authorizationCodeRequestAuthentication.getRedirectUri())){
Please ensure proper spacing.

2023-01-27 20:34 UTC, jgrandja commented
@leshalv As mentioned in this [comment](https://github.com/spring-projects/spring-authorization-server/pull/1013#pullrequestreview-1250596906), a test needs to be added as part of this PR. Are you able to add it?

2023-01-30 01:37 UTC, leshalv commented
> @leshalv As mentioned in this [comment](https://github.com/spring-projects/spring-authorization-server/pull/1013#pullrequestreview-1250596906), a test needs to be added as part of this PR. Are you able to add it?

Can you help me improve it?

2023-02-01 13:25 UTC, jgrandja commented
@leshalv 

> Can you help me improve it?

Do you need help with writing the test? Do you want me to write it and then merge?

2023-02-01 13:26 UTC, leshalv commented
> 

yes

2023-02-01 13:27 UTC, leshalv commented
> @leshalv
> 
> > Can you help me improve it?
> 
> Do you need help with writing the test? Do you want me to write it and then merge?

yes

2023-02-15 16:50 UTC, jgrandja commented
@leshalv Thanks again for reporting this. I added a polish commit with tests and is now merged.

2023-02-15 16:50 UTC, closed without merging