Using substring instead of replaceFirst
spring-projects/spring-authorization-server pull request #1223
Opened 2023-05-22 11:54 UTC by heartape

Close https://github.com/spring-projects/spring-authorization-server/issues/1222

2023-05-26 21:01 UTC, jgrandja requested changes
Thanks for the PR @heartape. Please see review comments.

2023-05-26 21:01 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/OAuth2AuthorizationConsent.java
> +				authorities.add(authority.getAuthority().substring(AUTHORITIES_SCOPE_PREFIX.length()));
> I conducted a simple test and achieved a 40 times performance improvement.

How did you conduct the test?

2023-05-27 06:11 UTC, heartape commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/OAuth2AuthorizationConsent.java
> +				authorities.add(authority.getAuthority().substring(AUTHORITIES_SCOPE_PREFIX.length()));
This is all the testing information：

```java
public static void main(String[] args) {
    String scope = "SCOPE_";
    String email = "SCOPE_email";
    int count = 10000000;

    long start1 = System.currentTimeMillis();
    for (int i = 0; i < count; i++) {
        String s = email.replaceFirst(scope, "");
    }
    long end1 = System.currentTimeMillis();
    System.out.println("replaceFirst : " + (end1 - start1));

    long start2 = System.currentTimeMillis();
    for (int i = 0; i < count; i++) {
        String s = email.substring(scope.length());
    }
    long end2 = System.currentTimeMillis();
    System.out.println("substring : " + (end2 - start2));
    System.out.println("count : " + count);
}
```
```
windows(8c16t 2G) idea 
java version "17.0.3.1" 2022-04-22 LTS
Java(TM) SE Runtime Environment (build 17.0.3.1+2-LTS-6)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3.1+2-LTS-6, mixed mode, sharing)

result:
replaceFirst : 2383
substring : 69
count : 10000000

###############################################################

centos7 vm(2c 2G)  command line 
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

result:
replaceFirst : 2856
substring : 107
count : 10000000
```

2023-05-27 06:38 UTC, heartape commented on CONTRIBUTING.adoc
> +. Keep the subject line to 50 characters or fewer if possible.
ok

2023-05-27 06:38 UTC, heartape commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/web/authentication/OidcLogoutAuthenticationConverter.java
> -		String sessionId = null;
ok

2023-05-29 01:48 UTC, heartape commented on CONTRIBUTING.adoc
> +. Keep the subject line to 50 characters or fewer if possible.
@jgrandja I will submit a new PR for this section. Do you think this is a good idea?

2023-05-29 13:37 UTC, jgrandja commented on CONTRIBUTING.adoc
> +. Keep the subject line to 50 characters or fewer if possible.
The use of "less" is proper grammar so we will leave as-is

2023-05-29 13:39 UTC, jgrandja commented
Thanks for the update @heartape. This is now merged.

2023-05-29 13:39 UTC, closed without merging