Fix issue with NPE on access token in OAuth2AuthorizationCodeAuthenticationProvider
spring-projects/spring-authorization-server pull request #1233
Opened 2023-05-25 13:14 UTC by pavelefros

Currently, (if access tokens are not persisted) line 159 can cause a NullPointerException, as we do not check if the access token is null, before calling `getToken()` on it. This issue occurs when trying to reuse authorization codes.

2023-05-30 15:24 UTC, jgrandja requested changes
Thank you for the fix @pavelefros. Please see the one review comment and also please add a test for the error scenario.

2023-05-30 15:24 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/OAuth2AuthorizationCodeAuthenticationProvider.java
> +				var token = authorization.getRefreshToken() != null ?
Please use `OAuth2Token` for the variable assignment

2023-06-09 14:07 UTC, pavelefros commented
Hi @jgrandja,
ok, sure, thanks! I will do the necessary and push the changes in the next few days.

2023-06-12 07:23 UTC, pavelefros commented
Hi @jgrandja,
I've added the explicit type and added a test.

2023-06-15 20:12 UTC, closed without merging

2023-06-15 20:15 UTC, jgrandja commented
Thanks for the updates @pavelefros. This is now merged along with a minor polish commit.