Adds how-to guide on adding authorities to access tokens
spring-projects/spring-authorization-server pull request #1264
Opened 2023-06-12 22:47 UTC by ddubson

Closes issue #542

2023-07-11 15:52 UTC, jgrandja requested changes
Thanks for the PR @ddubson ! Please see review comments.

Also, please rebase on `main`. Thanks!

2023-07-11 15:52 UTC, jgrandja commented on docs/src/docs/asciidoc/guides/how-to-custom-claims-authorities.adoc
> += How-to: Add authorities to custom claims in JWT-based access tokens
Please update to -> "How-to: Add authorities as custom claims in JWT access tokens"

2023-07-11 15:52 UTC, jgrandja commented on docs/src/docs/asciidoc/guides/how-to-custom-claims-authorities.adoc
> +[[how-to-extension-grant-type]]
Update to `how-to-custom-claims-authorities`

2023-07-11 15:52 UTC, jgrandja commented on docs/src/docs/asciidoc/guides/how-to-custom-claims-authorities.adoc
> +This guide demonstrates how to append resource owner authorities to a JSON Web Token (JWT)-based access token.
append -> add
JSON Web Token (JWT)-based access token -> JWT access token

2023-07-11 15:52 UTC, jgrandja commented on docs/src/docs/asciidoc/guides/how-to-custom-claims-authorities.adoc
> +The term 'authorities' may be described in varying forms such as roles, permissions, or groups of the resource owner.
Use double quotes for 'authorities'

may be described in varying forms -> may represent varying forms

2023-07-11 15:52 UTC, jgrandja commented on docs/src/docs/asciidoc/guides/how-to-custom-claims-authorities.adoc
> +To make resource owners' authorities available to the resource server, we add custom claims to an access token issued by Spring Authorization Server.
resource owners' -> resource owner's

2023-07-11 15:52 UTC, jgrandja commented on docs/src/docs/asciidoc/examples/src/main/java/sample/customClaims/authorities/CustomClaimsWithAuthoritiesConfiguration.java
> +					var roles = AuthorityUtils.authorityListToSet(context.getPrincipal().getAuthorities())
Replace `var` with `Set<String>`

2023-07-11 15:52 UTC, jgrandja commented on docs/src/docs/asciidoc/guides/how-to-custom-claims-authorities.adoc
> +<3> Define `OAuth2TokenCustomizer<JwtEncodingContext>` bean that allows for customizing JWT token claims.
bean -> `@Bean`

2023-07-11 15:52 UTC, jgrandja commented on docs/src/docs/asciidoc/guides/how-to-custom-claims-authorities.adoc
> +As a result of this customization, authorities information about the user will be included as a custom claim within an
within an access token -> within the access token

2023-07-13 15:26 UTC, ddubson commented
@jgrandja Thanks for the review! I've addressed the points outlined and rebased onto the latest Antora-based docs structure. Antora rendering looks great!

2023-07-19 22:29 UTC, jgrandja commented
Thanks for the updates @ddubson ! This is now merged along with a polish commit.

2023-07-19 22:29 UTC, closed without merging