Adds ability to inject custom metadata at client registration
spring-projects/spring-authorization-server pull request #1326
Opened 2023-08-02 18:31 UTC by ddubson

Currently contains commits for #1325 as a pre-requisite for introducing and running new test cases succesfully in the demo auth server.

✅ `./gradlew build`

Closes #1172

2023-08-16 22:14 UTC, jgrandja requested changes
Thanks for the PR @ddubson. Please see review comments.

2023-08-16 22:14 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/authentication/OidcClientRegistrationRegisteredClientConverter.java
> +public class OidcClientRegistrationRegisteredClientConverter implements Converter<OidcClientRegistration, RegisteredClient> {
Add javadoc

2023-08-16 22:14 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/authentication/OidcClientRegistrationRegisteredClientConverter.java
> +public class OidcClientRegistrationRegisteredClientConverter implements Converter<OidcClientRegistration, RegisteredClient> {
Make the class `final`. **NOTE:** This can still be reused using a delegation-based strategy.

2023-08-16 22:14 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/authentication/RegisteredClientOidcClientRegistrationConverter.java
> +public class RegisteredClientOidcClientRegistrationConverter implements Converter<RegisteredClient, OidcClientRegistration> {
Make the class `final`. **NOTE:** This can still be reused using a delegation-based strategy.

2023-08-16 22:14 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/oidc/authentication/RegisteredClientOidcClientRegistrationConverter.java
>   * @since 0.4.0
Update to `1.2.0`

2023-08-16 22:14 UTC, jgrandja commented on oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/config/annotation/web/configurers/OidcClientRegistrationTests.java
> +				.claim("custom-metadata-1", "value-1")
I'm not sure if we need to change the existing `custom-metadata-name-1` and `custom-metadata-name-2`? I would prefer minimal changes possible. Can we reuse existing custom claims input?

2023-08-16 22:14 UTC, jgrandja commented on oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/config/annotation/web/configurers/OidcClientRegistrationTests.java
>  				.isEqualTo("value-2");
We should also assert that `clientRegistrationResponse` includes the `custom-metadata-1` and `custom-metadata-1` claims in the response.

2023-08-17 13:27 UTC, ddubson commented
@jgrandja - I've applied all the suggested revisions to this PR - let me know if there are any further changes needed!

2023-08-18 15:06 UTC, jgrandja commented
@ddubson One more thing I forgot to mention. Can you move the 2x `Converter`'s from `*.oidc.authentication` to `*.oidc.converter`. Thanks.

2023-08-19 20:42 UTC, ddubson commented
Moved the converters to `*.oidc.converter` package as specified.

2023-09-13 20:35 UTC, jgrandja commented
Thanks for the PR @ddubson. This is now merged.

2023-09-13 20:35 UTC, closed without merging