Add Core Model / Components in ref doc
spring-projects/spring-authorization-server pull request #714
Opened 2022-05-02 17:29 UTC by jgrandja

Closes gh-671

2022-05-02 18:28 UTC, Buzzardo requested changes

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/core-model-components.adoc
> +<3> `authorities`: The authorities granted to the client by the resource owner. An authority can represent a scope, claim, permission, role, etc.
Change "a scope, claim, permission, role, etc." to "a scope, a claim, a permission, a role, and others."

Too many people (according to the studies I've read, about half) misinterpret "etc."

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/core-model-components.adoc
> +An `OAuth2TokenCustomizer` provides the capability to customize the attributes of an `OAuth2Token`, which are accessible in the provided <<oauth2-token-context, OAuth2TokenContext>>.
Change "capability" to "ability" (a change that can nearly always be made - "capability" is much overused).

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +In this guide, we will demonstrate how to implement the xref:{docs-dir}/core-model-components.adoc#core-model-components[core services] of xref:{docs-dir}/index.adoc#top[Spring Authorization Server]
Change to:

This guide shows how to implement the xref:{docs-dir}/core-model-components.adoc#core-model-components[core services] of xref:{docs-dir}/index.adoc#top[Spring Authorization Server] with JPA. The purpose of this guide is to provide a starting point for implementing these services yourself, with the intention that you can make modifications to suit your needs.

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +This guide seeks to provide a starting point for the data model and uses the simplest possible structure and data types. To come up with the initial schema, we begin by reviewing the xref:{docs-dir}/
Change "seeks to provide" to "provides" and remove "Please note:"

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
>  NOTE: Except for token, state, metadata, settings and claims values, we will use the JPA default column length of 255 for all columns. In reality, the length and even type of columns you use may need
Change to:

NOTE: Except for token, state, metadata, settings, and claims values, we use the JPA default column length of 255 for all columns. In reality, the length and even type of columns you use may need to be customized. You are encouraged to experiment and test before deploying to production.

(I know you didn't change this, but I just noticed it. Sorry.)

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +The xref:{docs-dir}/core-model-components.adoc#registered-client[`RegisteredClient`] domain object contains a few multi-valued fields and some settings fields that require storing arbitrary key/value
Change "The following is an example that we will use to create a JPA entity." to "The following example creates a JPA entity."

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +The xref:{docs-dir}/core-model-components.adoc#oauth2-authorization[`OAuth2Authorization`] domain object is more complex, and contains several multi-valued fields as well as numerous arbitrarily long
Remove the comma in "complex, and contains" (lists that have only two items do not get commas).

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +The xref:{docs-dir}/core-model-components.adoc#oauth2-authorization-consent[`OAuth2AuthorizationConsent`] domain object is the simplest to model, and only contains a single multi-valued field in addi
Change "to model, and only contains a single" to "to model and contains only a single" (that is, remove the command and move "only").

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +The following is an example of the `Client` entity which is used to persist information mapped from the xref:{docs-dir}/core-model-components.adoc#registered-client[`RegisteredClient`] domain object.
Change to:

The following listing shows the `Client` entity, which is used to persist information mapped from the xref:{docs-dir}/core-model-components.adoc#registered-client[`RegisteredClient`] domain object.

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +The following is an example of the `Authorization` entity which is used to persist information mapped from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization[`OAuth2Authorization`] d
Change to:

The following listing shows the `Authorization` entity, which is used to persist information mapped from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization[`OAuth2Authorization`] domain object.

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +The following is an example of the `AuthorizationConsent` entity which is used to persist information mapped from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization-consent[`OAuth2Au
Change to:

The following listing shows the `AuthorizationConsent` entity, which is used to persist information mapped from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization-consent[`OAuth2AuthorizationConsent`] domain object.

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +The following is an example of the `JpaRegisteredClientRepository` which uses a <<jpa-client-repository,`ClientRepository`>> for persisting a <<jpa-client-entity,`Client`>>, and maps to/from the xref
Change to:

The following listing shows the `JpaRegisteredClientRepository`, which uses a <<jpa-client-repository,`ClientRepository`>> for persisting a <<jpa-client-entity,`Client`>> and maps to and from the xref:{docs-dir}/core-model-components.adoc#registered-client[`RegisteredClient`] domain object.

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +The following is an example of the `JpaOAuth2AuthorizationService` which uses an <<jpa-authorization-repository,`AuthorizationRepository`>> for persisting an <<jpa-authorization-entity,`Authorization
Change to:

The following listing shows the `JpaOAuth2AuthorizationService`, which uses an <<jpa-authorization-repository,`AuthorizationRepository`>> for persisting an <<jpa-authorization-entity,`Authorization`>> and maps to and from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization[`OAuth2Authorization`] domain object.

2022-05-02 18:28 UTC, Buzzardo commented on docs/src/docs/asciidoc/guides/how-to-jpa.adoc
> +The following is an example of the `JpaOAuth2AuthorizationConsentService` which uses an <<jpa-authorization-consent-repository,`AuthorizationConsentRepository`>> for persisting an <<jpa-authorization
Change to:

The following listing shows the `JpaOAuth2AuthorizationConsentService`, which uses an <<jpa-authorization-consent-repository,`AuthorizationConsentRepository`>> for persisting an <<jpa-authorization-consent-entity,`AuthorizationConsent`>> and maps to and from the xref:{docs-dir}/core-model-components.adoc#oauth2-authorization-consent[`OAuth2AuthorizationConsent`] domain object.

2022-05-02 20:07 UTC, sjohnr reviewed
This is great, @jgrandja! I've added a couple of questions that could lead to improvements.

@Buzzardo, I can take the comments on the `how-to-jpa.adoc` and put them in a separate PR if @jgrandja agrees.

2022-05-02 20:14 UTC, Buzzardo commented
> @Buzzardo, I can take the comments on the `how-to-jpa.adoc` and put them in a separate PR if @jgrandja agrees.

Fine by me, so long as it works for you folks.

2022-05-03 10:58 UTC, jgrandja commented on docs/src/docs/asciidoc/core-model-components.adoc
> +<4> `clientSecret`: The client’s secret.
Good catch. I added a reference link

2022-05-03 15:48 UTC, closed without merging