validate client secret expired or not
spring-projects/spring-authorization-server pull request #862
Opened 2022-08-18 14:18 UTC by doctormacky

validate the client secret is expired or not.
see the details [here](https://github.com/spring-projects/spring-authorization-server/issues/850)

2022-08-19 01:22 UTC, doctormacky commented
@jgrandja Please help to review this PR. thanks!

2022-08-19 11:34 UTC, jgrandja requested changes
Thanks for the PR @doctormacky. Please see review comments.

Also, please add a test in `ClientSecretAuthenticationProviderTests`.

2022-08-19 11:34 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/ClientSecretAuthenticationProvider.java
> +		Instant expiredAt = registeredClient.getClientSecretExpiresAt();
Please move this validation below `if (!this.passwordEncoder.matches(clientSecret, registeredClient.getClientSecret()))`

2022-08-19 11:34 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/ClientSecretAuthenticationProvider.java
> +		Instant expiredAt = registeredClient.getClientSecretExpiresAt();
Remove the variable `expiredAt` and just use `registeredClient.getClientSecretExpiresAt()`

2022-08-19 11:34 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/authentication/ClientSecretAuthenticationProvider.java
> +		if (expiredAt!=null && Instant.now().isAfter(expiredAt)) {
Add spaces between the comparison `expiredAt!=null` so it's consistent with other code

2022-08-19 13:22 UTC, doctormacky commented
@jgrandja Please help to review it again.  thanks.

2022-08-24 01:45 UTC, doctormacky commented
@jgrandja Any progress on this PR ?

2022-08-24 20:53 UTC, jgrandja requested changes
Thanks for the updates @doctormacky.

One minor change left and we'll be ready to merge.

Can you also rebase off latest `0.4.x` and squash the commits.
Thanks!

2022-08-24 20:53 UTC, jgrandja commented on oauth2-authorization-server/src/test/java/org/springframework/security/oauth2/server/authorization/client/TestRegisteredClients.java
> +	public static RegisteredClient.Builder registeredClient4() {
Please remove this and reuse `TestRegisteredClients.registeredClient()`, which returns the `Builder` and allows you to update `clientSecretExpiresAt()`

2022-08-30 15:54 UTC, jgrandja commented
Thanks for the updates @doctormacky. This is now merged.

2022-08-30 15:54 UTC, closed without merging

2022-08-31 07:47 UTC, doctormacky commented
> Thanks for the updates @doctormacky. This is now merged.

Thanks @jgrandja  It's my pleasure.