Return registration_endpoint in OidcProviderConfigurationEndpointFilter
spring-projects/spring-authorization-server pull request #881
Opened 2022-09-02 14:02 UTC by sahariardev

Before: client registration endpoint was not retuned in oidc
Provider Configuration response

After: Returns client registration endpoint in oidcprovider configuration
response if client registration is enabled

Fixes gh-370

2022-09-02 14:03 UTC, sahariardev commented
Old PR link https://github.com/spring-projects/spring-authorization-server/pull/762

2022-09-03 10:31 UTC, sahariardev commented
Hi @jgrandja,
I have done all the changes. Please have a look.

2022-09-07 16:19 UTC, jgrandja requested changes
Thanks for the updates @sahariardev. Please see review comments.

2022-09-07 16:19 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/OAuth2AuthorizationServerMetadataClaimNames.java
> +	 */
Add `@since 0.4.0`

2022-09-07 16:19 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/AbstractOAuth2AuthorizationServerMetadata.java
> +		public B clientRegistrationEndpoint(String clientRegistrationEndpoint) {
Move this just below `tokenIntrospectionEndpointAuthenticationMethods()`

2022-09-07 16:19 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/OAuth2AuthorizationServerMetadataClaimNames.java
> +	public static final String REGISTRATION_ENDPOINT = "registration_endpoint";
Move this just below `INTROSPECTION_ENDPOINT_AUTH_METHODS_SUPPORTED`

2022-09-07 16:19 UTC, jgrandja commented on oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/server/authorization/AbstractOAuth2AuthorizationServerMetadata.java
> +		public B clientRegistrationEndpoint(String clientRegistrationEndpoint) {
The getter needs to be added to `OAuth2AuthorizationServerMetadataClaimAccessor.getClientRegistrationEndpoint()`

2022-09-09 12:56 UTC, sahariardev commented
Hi @jgrandja,
I have done all the changes.
Thanks.

2022-09-20 16:36 UTC, jgrandja commented
Thanks for all the updates @sahariardev. This is now merged.

FYI, I added a polish commit with some minor updates.
Thanks again!

2022-09-20 16:36 UTC, closed without merging